### PR TITLE
Add operator Containerfile for Konflux

### PR DESCRIPTION
**Pull request by yuumasato**
Add initial Containerfile to build the File Integrity Operator in Konflux.

### CODE REVIEW

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by rhmdnd** [comment]
This should hopefully clear up the ROSA failures - https://github.com/openshift/release/pull/57825

**Comment by rhmdnd** [comment]
Setting the bundle and bundle upgrade tests to optional in https://github.com/openshift/release/pull/57826

**Pull request merged**
