### PR TITLE
Release v1.3.1

### PR DESCRIPTION
**Pull request by rhmdnd**

### CODE REVIEW

**Comment by rhmdnd** [comment]
PR to update the pullspec for version 1.3.1

https://github.com/openshift/release/pull/41633

**Comment by rhmdnd** [comment]
This needs to be rebased and retagged.

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
@rhmdnd Thank you for the great change notes at the top!

**Pull request closed without merging**
