### PR TITLE
Release v0.1.31

### PR DESCRIPTION
**Pull request by rhmdnd**

### CODE REVIEW

**Comment by mrogers950** [comment]
Looks like the cluster was degraded.
/retest

**Comment by mrogers950** [comment]
It looks like we're trying to upgrade from .31 to .31:

```
subscription.operators.coreos.com/oo-5vbx2 patched
Subscription channel updated and installPlan set to Automatic
Waiting for ClusterServiceVersion to become ready...
Timed out waiting for csv to become ready
Dumping Namespace file-integrity as /logs/artifacts/ns-file-integrity.yaml
Dumping Subscription oo-5vbx2 as /logs/artifacts/sub-oo-5vbx2.yaml
  Subscription oo-5vbx2 status state: AtLatestKnown
ClusterServiceVersion file-integrity-operator.v0.1.31 was created but never became ready
Dumping ClusterServiceVersion file-integrity-operator.v0.1.31 as /logs/artifacts/csv-file-integrity-operator.v0.1.31.yaml
  ClusterServiceVersion file-integrity-operator.v0.1.31 status phase: Succeeded
  ClusterServiceVersion file-integrity-operator.v0.1.31 status message: install strategy completed with no errors
  ClusterServiceVersion file-integrity-operator.v0.1.31 status reason: InstallSucceeded
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-10-18T19:06:04Z"}
error: failed to execute wrapped command: exit status 1 
INFO[2022-10-18T19:06:09Z] Step e2e-bundle-aws-upgrade-optional-operators-ci-upgrade failed after 30m30s. 
INFO[2022-10-18T19:06:09Z] Step phase pre failed after 1h10m10s.        
INFO[2022-10-18T19:06:09Z] Running multi-stage phase post               
INFO[2022-10-18T19:06:09Z] Running step e2e-bundle-aws-upgrade-gather-aws-console. 
INFO[2022-10-18T19:06:29Z] Step e2e-bundle-aws-upgrade-gather-aws-console succeeded after 20s. 
INFO[2022-10-18T19:06:29Z] Running step e2e-bundle-aws-upgrade-gather-must-gather. 
INFO[2022-10-18T19:08:39Z] Step e2e-bundle-aws-upgrade-gather-must-gather succeeded after 2m10s. 
INFO[2022-10-18T19:08:39Z] Running step e2e-bundle-aws-upgrade-gather-extra. 
INFO[2022-10-18T19:11:09Z] Step e2e-bundle-aws-upgrade-gather-extra succeeded after 2m30s. 
INFO[2022-10-18T19:11:09Z] Running step e2e-bundle-aws-upgrade-gather-audit-logs. 
INFO[2022-10-18T19:11:39Z] Step e2e-bundle-aws-upgrade-gather-audit-logs succeeded after 30s. 
INFO[2022-10-18T19:11:39Z] Running step e2e-bundle-aws-upgrade-ipi-deprovision-deprovision. 
INFO[2022-10-18T19:17:29Z] Step e2e-bundle-aws-upgrade-ipi-deprovision-deprovision succeeded after 5m50s. 
INFO[2022-10-18T19:17:29Z] Step phase post succeeded after 11m20s.      
INFO[2022-10-18T19:17:29Z] Releasing leases for test e2e-bundle-aws-upgrade 
INFO[2022-10-18T19:17:30Z] Ran for 1h58m[55](https://prow.ci.openshift.org/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gs%2Forigin-ci-test%2Fpr-logs%2Fpull%2Fopenshift_file-integrity-operator%2F289%2Fpull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws-upgrade%2F1582420847174356992%22%7D&topURL=https%3A//prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/289/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws-upgrade/1582420847174356992&lensIndex=1#build-log.txt:55)s                             
ERRO[2022-10-18T19:17:30Z] Some steps failed:                           
ERRO[2022-10-18T19:17:30Z] 
  * could not run steps: step e2e-bundle-aws-upgrade failed: "e2e-bundle-aws-upgrade" pre steps failed: "e2e-bundle-aws-upgrade" pod "e2e-bundle-aws-upgrade-optional-operators-ci-upgrade" failed: the pod ci-op-h4qlpjvz/e2e-bundle-aws-upgrade-optional-operators-ci-upgrade failed after 30m26s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
---
Set the deployment upgrade start time: 2022-10-18T18:35:45Z
subscription.operators.coreos.com/oo-5vbx2 patched
Subscription channel updated and installPlan set to Automatic
Waiting for ClusterServiceVersion to become ready...
Timed out waiting for csv to become ready
Dumping Namespace file-integrity as /logs/artifacts/ns-file-integrity.yaml
Dumping Subscription oo-5vbx2 as /logs/artifacts/sub-oo-5vbx2.yaml
  Subscription oo-5vbx2 status state: AtLatestKnown
ClusterServiceVersion file-integrity-operator.v0.1.31 was created but never became ready
Dumping ClusterServiceVersion file-integrity-operator.v0.1.31 as /logs/artifacts/csv-file-integrity-operator.v0.1.31.yaml
  ClusterServiceVersion file-integrity-operator.v0.1.31 status phase: Succeeded
  ClusterServiceVersion file-integrity-operator.v0.1.31 status message: install strategy completed with no errors
  ClusterServiceVersion file-integrity-operator.v0.1.31 status reason: InstallSucceeded
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-10-18T19:06:04Z"}
error: failed to execute wrapped command: exit status 1
---
Link to step on registry info site: https://steps.ci.openshift.org/reference/optional-operators-ci-upgrade
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift&repo=file-integrity-operator&branch=master&test=e2e-bundle-aws-upgrade 
INFO[2022-10-18T19:17:30Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:utilizing_lease:executing_test:executing_multi_stage_test'
```

**Comment by rhmdnd** [comment]
> It looks like we're trying to upgrade from .31 to .31:

That's odd since we appear to be explicit in starting at 0.1.30:

https://github.com/openshift/release/blob/9d3238e276eae2f546386d285897e630b68314fa/ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.13.yaml#L103

**Comment by rhmdnd** [comment]
/retest

We just landed a potential fix to get upgrades working again in https://github.com/openshift/release/pull/33261

**Pull request merged**
