### PR TITLE
bump(*): Vendor dependencies

### PR DESCRIPTION
**Pull request by tnozicka**
This ensures offline builds and ensures the project requirements are met.

Also the project level golang builder is about to be switched to force vendoring mode.

/priority critical-urgent
/assign jhrozek JAORMX mrogers950

### CODE REVIEW

**Comment by tnozicka** [comment]
this seems valid
```
Error: failed to build test binary: (failed to exec []string{"go", "test", "-mod=vendor", "./tests/e2e/...", "-namespacedMan", "/tmp/namespaced-manifest.yaml208083209", "-globalMan", "/tmp/global-manifest.yaml504214228", "-root", "/go/src/github.com/openshift/file-integrity-operator", "-v", "-singleNamespace", "-parallel=1"}: exit status 1)
Usage:
  operator-sdk test local <path to tests directory> [flags]
Flags:
      --debug                         Enable debug-level logging
      --global-manifest string        Path to manifest for Global resources (e.g. CRD manifests)
      --go-test-flags string          Additional flags to pass to go test
  -h, --help                          help for local
      --image string                  Use a different operator image from the one specified in the namespaced manifest
      --kubeconfig string             Kubeconfig path
      --local-operator-flags string   The flags that the operator needs (while using --up-local). Example: "--flag1 value1 --flag2=value2"
      --molecule-test-flags string    Additional flags to pass to molecule test
      --namespace string              If non-empty, single namespace to run tests in
      --namespaced-manifest string    Path to manifest for per-test, namespaced resources (e.g. RBAC and Operator manifest)
      --no-setup                      Disable test resource creation
      --up-local                      Enable running operator locally with go run instead of as an image in the cluster
Global Flags:
      --verbose   Enable verbose logging
make: *** [e2e] Error 1
```

**Comment by tnozicka** [comment]
/hold
the failure seems persistent and possibly related, not sure

**Comment by mrogers950** [comment]
@tnozicka https://github.com/openshift/file-integrity-operator/pull/17 should fix our test flake. please rebase once it merges.

**Comment by tnozicka** [comment]
rebased
/hold cancel

**Comment by tnozicka** [comment]
it seems to be failing still and not just this PR, also master with https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6337/rehearse-6337-pull-ci-openshift-file-integrity-operator-master-e2e-aws/3

**Comment by JAORMX** [comment]
This is weird, the test passes locally... but then again, locally it's no using the vendor directory yet.

**Comment by tnozicka** [comment]
closing in favor of https://github.com/openshift/file-integrity-operator/pull/19

**Pull request closed without merging**
