### PR TITLE
CSV: We support FIPS

### PR DESCRIPTION
**Pull request by jhrozek**
Let's advertise the features we test and support through the CSV.

Jira: [CMP-1164](https://issues.redhat.com/browse/CMP-1164)

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm

**Comment by mrogers950** [comment]
@jhrozek can you add to the commit message that you also correct the disconnected annotation to lowercase?

**Comment by jhrozek** [comment]
On Tue, Jan 18, 2022 at 08:19:10AM -0800, Matt Rogers wrote:
> @jhrozek can you add to the commit message that you also correct the disconnected annotation to lowercase?

Sure, done.

**Pull request merged**
