### PR TITLE
Release v1.3.0

### PR DESCRIPTION
**Pull request by rhmdnd**

### CODE REVIEW

**Comment by jhrozek** [comment]
the contents of the PR look. I opened https://github.com/openshift/release/pull/40212 to use the upcoming pullspec

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by rhmdnd** [comment]
> the contents of the PR look. I opened [openshift/release#40212](https://github.com/openshift/release/pull/40212) to use the upcoming pullspec

Thanks, I'll kick the pullspec PR through once it passes.

**Comment by rhmdnd** [comment]
https://github.com/openshift/release/pull/40212 landed

**Comment by jhrozek** [comment]
@GroceryBoyJr PTAL for doc-approved

**Pull request merged**
