### PR TITLE
Bump golang dependency to 1.19

### PR DESCRIPTION
**Pull request by rhmdnd**
We were using 1.16, which ended support 11 months ago. Let's update the
version of go we use and also update the dependencies we use (fixing
vulnerabilities caught by dependabot).

You can verify the contents of this commit using:

  $ make clean // bump go version in go.mod
  $ go get -u all  // fix resolution issues manually
  $ go mod go_mod
  $ go mod vendor

### CODE REVIEW

**Comment by rhmdnd** [comment]
Bumping golang version for CI here - https://github.com/openshift/release/pull/36861

**Comment by rhmdnd** [comment]
> so it looks like we also need to update `Dockerfile.ci` and tell it to use `rhel-8-release-golang-1.19-openshift-4.12` instead?

Aha - good call. I forgot about that hook.

Thanks!

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
