### PR TITLE
Turn logcollector into an operator sub-command

### PR DESCRIPTION
**Pull request by mrogers950**
This splits the operator binary into two sub-commands: `operator` and
`logcollector`, and removes the building/pushing of the logcollector images.
References to the logcollector image are replaced by the operator image, and
run with an invocation of the logcollector sub-command.

### CODE REVIEW

**Comment by mrogers950** [comment]
Looks like I will still need to build a logcollector dummy image to satisfy CI at the moment.

**Comment by mrogers950** [comment]
@JAORMX @jhrozek please review, I plan on giving CO the same treatment.

**Comment by jhrozek** [comment]
I'm going to merge this PR in order to rebase the other PRs atop.

**Pull request merged**
