### PR TITLE
Added code changes for image to support ppc64le

### PR DESCRIPTION
**Pull request by gauravpbankar**
Raising a PR for building image for ppc64le

### CODE REVIEW

**Comment by mrogers950** [comment]
@gauravpbankar we'll also need a [CSV label for the arches](https://docs.openshift.com/container-platform/4.10/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-multi-arch_osdk-generating-csvs) added to config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml

**Comment by gauravpbankar** [comment]
> @gauravpbankar we'll also need a [CSV label for the arches](https://docs.openshift.com/container-platform/4.10/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-multi-arch_osdk-generating-csvs) added to config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml

@mrogers950 I have added those CSV label for the arches. Please review it.

**Pull request merged**
