### PR TITLE
Added GithubCI to build  multi-arch image

### PR DESCRIPTION
**Pull request by gauravpbankar**
Raising a PR for building multi-arch images through Github action CI.

Created Github CI which can have github action and qemu statis user on top of x86 arch and we are using binaries of Power and other archs which are enabling us to create Virtual env for those architectures by this way we are building multi-arch images.

Note: To make it work need to create below two secrets in github repo 

**- QUAY_USER ---> quay username**
**- QUAY_PWD  ---> quay repo password**

### CODE REVIEW

**Comment by mrogers950** [comment]
Hi @gauravpbankar, thanks for the PR. Unfortunately, the openshift github org does not have actions enabled. We've explored this before, and the response from the DPP team is that actions will not be enabled any time soon :(

**Comment by gauravpbankar** [comment]
@mrogers950  if we are not going to support any CI for buiding multi-arch image then what will be the best approach to get support for Power?

**Comment by JAORMX** [comment]
@gauravpbankar note that this would only be for upstream builds. Downstream builds are handled by an entirely different pipeline, so supporting Power is not limited by what's available in this GH repo/org.

**Comment by mrogers950** [comment]
@gauravpbankar like @JAORMX mentioned, we can aim for supporting Power with images that we build internally for the Red Hat catalog. The quay.io images that we provide here are mostly for convenience and testing.

**Pull request closed without merging**
