### PR TITLE
Bug 2115821: Fix controller metrics port

### PR DESCRIPTION
**Pull request by mrogers950**
- Run the controller-runtime metrics (controller workload stats) on port 8383.
- Remove the service endpoint for http-metrics. This was previously an additional metrics endpoint provided by operator-sdk, but was only useful for proxy programs. controller-runtime now only provides controller workqueue metrics.
- Ensure the metrics service is updated on operator startup. In turn this will update the ServiceMonitor for new changes to the service endpoints.

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2115821

### CODE REVIEW

**Review by rhmdnd — COMMENTED** [review]
Looks like a reasonable change. Any idea how we can test this in CI?

**Comment by mrogers950** [comment]
> Looks like a reasonable change. Any idea how we can test this in CI?

We could add a test that curls against the endpoint to check that its running (we already CI test the custom metrics). But this would really be testing that controller-runtime started the default metrics listener. not sure that is too useful.

**Comment by mrogers950** [comment]
Hm, the bundle jobs fail like:
```
INFO[[2](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A2)022-08-09T18:47:36Z] ci-operator version v20220808-69551b8c6      
INFO[2022-08-09T18:47:36Z] Loading configuration from https://config.ci.openshift.org/ for openshift/file-integrity-operator@master 
INFO[2022-08-09T18:47:[3](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A3)7Z] Resolved source https://github.com/openshift/file-integrity-operator to master@23cc55ea, merging: #278 fb9ceb68 @mrogers950 
INFO[2022-08-09T18:[4](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A4)7:37Z] Building release initial from a snapshot of ocp/4.12 
INFO[2022-08-09T18:47:37Z] Building release latest from a snapshot of ocp/4.12 
INFO[2022-08-09T18:47:37Z] Using namespace https://console-openshift-console.apps.build03.ky4t.p1.openshiftapps.com/k8s/cluster/projects/ci-op-9rpkcvki 
INFO[2022-08-09T18:47:37Z] Running [input:root], [input:openshift_release_rhel-8-release-golang-1.17-openshift-4.10], [input:operator-index], [input:origin-centos-8], [input:ocp-4.[5](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A5)-upi-installer], [release-inputs:initial], [release-inputs:latest], src, file-integrity-operator, [output:stable:file-integrity-operator], [images], src-bundle, file-integrity-operator-bundle, ci-index-file-integrity-operator-bundle-gen, [release:latest], ci-index-file-integrity-operator-bundle, e2e-bundle-aws 
INFO[2022-08-09T18:47:37Z] Tagging origin/centos:8 into pipeline:origin-centos-8. 
INFO[2022-08-09T18:47:37Z] Tagging openshift/release:rhel-8-release-golang-1.17-openshift-4.10 into pipeline:root. 
INFO[2022-08-09T18:47:37Z] Tagging ocp/4.5:upi-installer into pipeline:ocp-4.5-upi-installer. 
INFO[2022-08-09T18:47:37Z] Tagging ci/redhat-operator-index:v4.10 into pipeline:operator-index. 
INFO[2022-08-09T18:47:37Z] Tagging openshift/release:rhel-8-release-golang-1.17-openshift-4.10 into pipeline:openshift_release_rhel-8-release-golang-1.17-openshift-4.10. 
INFO[2022-08-09T18:47:37Z] Building src                                 
INFO[2022-08-09T18:48:52Z] Build src succeeded after 1m11s              
INFO[2022-08-09T18:48:52Z] Building file-integrity-operator             
INFO[2022-08-09T18:52:52Z] Build file-integrity-operator succeeded after 4m4s 
INFO[2022-08-09T18:52:52Z] Tagging file-integrity-operator into stable  
INFO[2022-08-09T18:52:52Z] Building src-bundle                          
INFO[2022-08-09T18:52:52Z] Creating release image registry.build03.ci.openshift.org/ci-op-9rpkcvki/release:latest. 
INFO[2022-08-09T18:54:12Z] Snapshot integration stream into release 4.12.0-0.ci.test-2022-08-09-185252-ci-op-9rpkcvki-latest to tag release:latest  
INFO[2022-08-09T18:57:02Z] Build src-bundle succeeded after 4m7s        
INFO[2022-08-09T18:57:02Z] Building file-integrity-operator-bundle      
INFO[2022-08-09T18:59:57Z] Build file-integrity-operator-bundle succeeded after 2m54s 
INFO[2022-08-09T18:59:57Z] Building ci-index-file-integrity-operator-bundle-gen 
INFO[2022-08-09T19:03:18Z] Build ci-index-file-integrity-operator-bundle-gen failed, printing logs: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
100     2    0     2    0     0      0      0 --:--:--  0:00:05 --:--:--     0
Caching blobs under "/var/cache/blobs".
Trying to pull image-registry.openshift-image-registry.svc:5000/ci-op-9rpkcvki/pipeline@sha25[6](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A6):56e228e5a[7](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A7)b38533be5b8cb30a5afe840134a904a45ae5d862c6378a6b83acbd...
Getting image source signatures
Copying blob sha256:3187a4d7cffda2d88601e3f1bf2053f4146470bffffdfe559e327d912983d563
Copying blob sha256:f701c99ce1d219565c3a9c59e7d12135bf3d73573aaa7f98a99901d373195e1e
Copying blob sha256:47aa3ed2034c4f27622b989b26c06087de17067268a19a1b3642a7e2686cd1a3
Copying blob sha256:eac1b95df832dc9f172fd1f07e7cb50c1929b118a4249ddd02c6318a677b506a
Copying blob sha256:56908b3674bda35f871058853518c895224107b74865114d1a5076b551728e2d
Copying blob sha256:ef503745f8f23498e5b2da734b66ec3c444bed3da83b1a6120ef9f7c1e36597b
Copying blob sha256:56908b3674bda35f871058853518c895224107b74865114d1a5076b551728e2d
Copying blob sha256:3187a4d7cffda2d88601e3f1bf2053f4146470bffffdfe559e327d912983d563
Copying blob sha256:47aa3ed2034c4f27622b989b26c06087de17067268a19a1b3642a7e2686cd1a3
Copying blob sha256:ef503745f8f23498e5b2da734b66ec3c444bed3da83b1a6120ef9f7c1e36597b
Copying blob sha256:f701c99ce1d219565c3a9c59e7d12135bf3d73573aaa7f98a99901d373195e1e
Copying blob sha256:eac1b95df832dc9f172fd1f07e7cb50c1929b118a4249ddd02c6318a677b506a
Copying config sha256:07de87824f72a75e269de5cb599dcd9ed99a83c6acc2670b5cddcd31edeeb513
Writing manifest to image destination
Storing signatures
Replaced Dockerfile FROM image pipeline:src
time="2022-08-09T19:02:41Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
I0809 19:02:41.047696       1 defaults.go:102] Defaulting to storage driver "overlay" with options [mountopt=metacopy=on].
Caching blobs under "/var/cache/blobs".
Pulling image image-registry.openshift-image-registry.svc:5000/ci-op-9rpkcvki/pipeline@sha256:56e228e5a7b38533be5b8cb30a5afe840134a904a45ae5d862c6378a6b83acbd ...
Pulling image quay.io/operator-framework/upstream-opm-builder ...
Trying to pull quay.io/operator-framework/upstream-opm-builder:latest...
Getting image source signatures
Copying blob sha256:29291e31a76a7e560b9b7ad3cada56e8c18d50a96cca8a2573e4f4689d7aca77
Copying blob sha256:c66c683f6df7971589dd1dd680dadbb8f04f3d993bbaaf355d73242730d2038a
Copying blob sha256:61b002961e1019ee886e719c5dc49a0bb94f462215b20a9f183ce132a858bd3e
Copying blob sha256:f254a54481e419dc0f67364fca0f78289f0a52490e96d62255afdfad394d70cd
Copying blob sha256:a5b73dd03989de330afe564ecaf854e4a99ac63322cb7731b1b69dbb418db600
Copying config sha256:666cfd655d66771c4cca8ce3dedf07717a3ac4ac8ad5b294cfcb1330791c2468
Writing manifest to image destination
Storing signatures
Adding transient rw bind mount for /run/secrets/rhsm
[1/2] STEP 1/6: FROM quay.io/operator-framework/upstream-opm-builder AS builder
Trying to pull quay.io/operator-framework/upstream-opm-builder:latest...
Getting image source signatures
Copying blob sha256:61b002961e1019ee886e719c5dc49a0bb94f462215b20a9f183ce132a858bd3e
Copying blob sha256:c66c683f6df7971589dd1dd680dadbb8f04f3d993bbaaf355d73242730d2038a
Copying blob sha256:29291e31a76a7e560b9b7ad3cada56e8c18d50a96cca8a2573e4f4689d7aca77
Copying blob sha256:f254a54481e419dc0f67364fca0f78289f0a52490e96d62255afdfad394d70cd
Copying blob sha256:a5b73dd03989de330afe564ecaf854e4a99ac63322cb7731b1b69dbb418db600
Copying config sha256:666cfd655d66771c4cca8ce3dedf07717a3ac4ac8ad5b294cfcb1330791c2468
Writing manifest to image destination
Storing signatures
[1/2] STEP 2/6: ENV "BUILD_LOGLEVEL"="0"
[1/2] STEP 3/6: COPY .dockerconfigjson .
[1/2] STEP 4/6: RUN mkdir $HOME/.docker && mv .dockerconfigjson $HOME/.docker/config.json
[1/2] STEP 5/6: RUN ["opm","index","add","--mode","replaces","--bundles","registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:7c8f42a9afc657bc9d53fbe0824badbc6541a9767b6ac9ce0cf2a4afca913387","--out-dockerfile","index.Dockerfile","--generate","--from-index","registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:67e1fecc5bdbf75c0b00e3138402952ec8f0d0b71ed16349531dd0e62b0d8371"]
time="2022-08-09T19:02:59Z" level=warning msg="\x1b[1;33mDEPRECATION NOTICE:\nSqlite-based catalogs and their related subcommands are deprecated. Support for\nthem will be removed in a future release. Please migrate your catalog workflows\nto the new file-based catalog format.\x1b[0m"
time="2022-08-09T19:02:59Z" level=info msg="building the index" bundles="[registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:7c8f42a9afc657bc9d53fbe0824badbc6541a9767b6ac9ce0cf2a4afca913387]"
time="2022-08-09T19:02:59Z" level=info msg="Pulling previous image registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:67e1fecc5bdbf75c0b00e3138402952ec8f0d0b71ed16349531dd0e62b0d8371 to get metadata" bundles="[registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:7c8f42a9afc657bc9d53fbe0824badbc6541a9767b6ac9ce0cf2a4afca913387]"
time="2022-08-09T19:03:02Z" level=warning msg="{\"created\":\"2022-08-09T11:10:53.078190808Z\",\"container\":\"31eaee765484fa8da0faaa043840b83573c51794e421dbadff453167ac623378\",\"container_config\":{\"Hostname\":\"c07ed41fe7ec\",\"Domainname\":\"\",\"User\":\"1001\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"ExposedPorts\":{\"50051/tcp\":{}},\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"__doozer=merge\",\"BUILD_RELEASE=202206100236.p0.gc10b001.assembly.stream\",\"BUILD_VERSION=v4.10.0\",\"OS_GIT_MAJOR=4\",\"OS_GIT_MINOR=10\",\"OS_GIT_PATCH=0\",\"OS_GIT_TREE_STATE=clean\",\"OS_GIT_VERSION=4.10.0-202206100236.p0.gc10b001.assembly.stream-c10b001\",\"SOURCE_GIT_TREE_STATE=clean\",\"OS_GIT_COMMIT=c10b001\",\"SOURCE_DATE_EPOCH=1654826305\",\"SOURCE_GIT_COMMIT=c10b001a30646331083c2e03f5790616f47a69a8\",\"SOURCE_GIT_TAG=c10b001a3\",\"SOURCE_GIT_URL=https://github.com/openshift/operator-framework-olm\",\"GODEBUG=x509ignoreCN=0,madvdontneed=1\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"container=oci\"],\"Cmd\":[\"registry\",\"serve\",\"--database\",\"/database/index.db\"],\"ArgsEscaped\":true,\"Image\":\"\",\"Volumes\":{},\"WorkingDir\":\"/registry\",\"Entrypoint\":[\"/bin/opm\"],\"OnBuild\":[],\"Labels\":{\"License\":\"GPLv2+\",\"architecture\":\"x86_64\",\"build-date\":\"2022-06-10T06:07:54.996203\",\"com.redhat.build-host\":\"cpt-1001.osbs.prod.upshift.rdu2.redhat.com\",\"com.redhat.component\":\"operator-registry-container\",\"com.redhat.index.delivery.distribution_scope\":\"prod\",\"com.redhat.index.delivery.version\":\"v4.10\",\"com.redhat.license_terms\":\"https://www.redhat.com/agreements\",\"description\":\"This is a component of OpenShift Operator Lifecycle Manager and is the base for operator catalog API containers.\",\"distribution-scope\":\"public\",\"io.buildah.version\":\"1.24.2\",\"io.k8s.description\":\"This is a component of OpenShift Operator Lifecycle Manager and is the base for operator catalog API containers.\",\"io.k8s.display-name\":\"OpenShift Operator Registry\",\"io.openshift.build.commit.id\":\"c10b001a30646331083c2e03f5790616f47a69a8\",\"io.openshift.build.commit.url\":\"https://github.com/openshift/operator-framework-olm/commit/c10b001a30646331083c2e03f5790616f47a69a8\",\"io.openshift.build.source-location\":\"https://github.com/openshift/operator-framework-olm\",\"io.openshift.expose-services\":\"\",\"io.openshift.maintainer.component\":\"OLM\",\"io.openshift.maintainer.product\":\"OpenShift Container Platform\",\"io.openshift.tags\":\"openshift,base\",\"maintainer\":\"Odin Team \\u003caos-odin@redhat.com\\u003e\",\"name\":\"openshift/ose-operator-registry\",\"operators.operatorframework.io.index.database.v1\":\"/database/index.db\",\"release\":\"202206100236.p0.gc10b001.assembly.stream\",\"summary\":\"Operator Registry runs in a Kubernetes or OpenShift cluster to provide operator catalog data to Operator Lifecycle Manager.\",\"url\":\"https://access.redhat.com/containers/#/registry.access.redhat.com/openshift/ose-operator-registry/images/v4.10.0-202206100236.p0.gc10b001.assembly.stream\",\"vcs-ref\":\"bb0540e80199b2435d6c8e0599857f1a75af274d\",\"vcs-type\":\"git\",\"vendor\":\"Red Hat, Inc.\",\"version\":\"v4.10.0\"}},\"config\":{\"Hostname\":\"c07ed41fe7ec\",\"Domainname\":\"\",\"User\":\"1001\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"ExposedPorts\":{\"50051/tcp\":{}},\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"__doozer=merge\",\"BUILD_RELEASE=202206100236.p0.gc10b001.assembly.stream\",\"BUILD_VERSION=v4.10.0\",\"OS_GIT_MAJOR=4\",\"OS_GIT_MINOR=10\",\"OS_GIT_PATCH=0\",\"OS_GIT_TREE_STATE=clean\",\"OS_GIT_VERSION=4.10.0-202206100236.p0.gc10b001.assembly.stream-c10b001\",\"SOURCE_GIT_TREE_STATE=clean\",\"OS_GIT_COMMIT=c10b001\",\"SOURCE_DATE_EPOCH=1654826305\",\"SOURCE_GIT_COMMIT=c10b001a30646331083c2e03f5790616f47a69a8\",\"SOURCE_GIT_TAG=c10b001a3\",\"SOURCE_GIT_URL=https://github.com/openshift/operator-framework-olm\",\"GODEBUG=x509ignoreCN=0,madvdontneed=1\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"container=oci\"],\"Cmd\":[\"registry\",\"serve\",\"--database\",\"/database/index.db\"],\"ArgsEscaped\":true,\"Image\":\"\",\"Volumes\":{},\"WorkingDir\":\"/registry\",\"Entrypoint\":[\"/bin/opm\"],\"OnBuild\":[],\"Labels\":{\"License\":\"GPLv2+\",\"architecture\":\"x86_64\",\"build-date\":\"2022-06-10T06:07:54.996203\",\"com.redhat.build-host\":\"cpt-1001.osbs.prod.upshift.rdu2.redhat.com\",\"com.redhat.component\":\"operator-registry-container\",\"com.redhat.index.delivery.distribution_scope\":\"prod\",\"com.redhat.index.delivery.version\":\"v4.10\",\"com.redhat.license_terms\":\"https://www.redhat.com/agreements\",\"description\":\"This is a component of OpenShift Operator Lifecycle Manager and is the base for operator catalog API containers.\",\"distribution-scope\":\"public\",\"io.buildah.version\":\"1.24.2\",\"io.k8s.description\":\"This is a component of OpenShift Operator Lifecycle Manager and is the base for operator catalog API containers.\",\"io.k8s.display-name\":\"OpenShift Operator Registry\",\"io.openshift.build.commit.id\":\"c10b001a30646331083c2e03f5790616f47a69a8\",\"io.openshift.build.commit.url\":\"https://github.com/openshift/operator-framework-olm/commit/c10b001a30646331083c2e03f5790616f47a69a8\",\"io.openshift.build.source-location\":\"https://github.com/openshift/operator-framework-olm\",\"io.openshift.expose-services\":\"\",\"io.openshift.maintainer.component\":\"OLM\",\"io.openshift.maintainer.product\":\"OpenShift Container Platform\",\"io.openshift.tags\":\"openshift,base\",\"maintainer\":\"Odin Team \\u003caos-odin@redhat.com\\u003e\",\"name\":\"openshift/ose-operator-registry\",\"operators.operatorframework.io.index.database.v1\":\"/database/index.db\",\"release\":\"202206100236.p0.gc10b001.assembly.stream\",\"summary\":\"Operator Registry runs in a Kubernetes or OpenShift cluster to provide operator catalog data to Operator Lifecycle Manager.\",\"url\":\"https://access.redhat.com/containers/#/registry.access.redhat.com/openshift/ose-operator-registry/images/v4.10.0-202206100236.p0.gc10b001.assembly.stream\",\"vcs-ref\":\"bb0540e80199b2435d6c8e0599857f1a75af274d\",\"vcs-type\":\"git\",\"vendor\":\"Red Hat, Inc.\",\"version\":\"v4.10.0\"}},\"architecture\":\"amd64\",\"os\":\"linux\",\"parent\":\"sha256:a462910d4a0ea5fd6bbfe9468e5223bb2193e5ea26f14e076aeb3c27267ac46a\",\"rootfs\":{\"type\":\"layers\",\"diff_ids\":[\"sha256:35db14176a6cdc336dc7280e261517570724f4e03784c40471cacbe796467162\",\"sha256:e767386b141e1d2a2f10dadada9929ab79b8e2c911b3bb2fcfa3136e74cbeb1c\",\"sha256:eb13b93b3eea3de0f31496daa1b74a727ff237603d79150f031308b4695c4828\",\"sha256:2dc440b86fb941d93df9d280df2daf3a9ad42fb452a8c8f81840d6e3974ae816\",\"sha256:e4cab34496770fefc0dfdb8dc1b8ea2a9f850c6df903ac95d0dc1641e85429b1\",\"sha256:39cbbcf163e23716a5b2ee432192204b14bd2b0bf8fce052e773a0b384e5a9d9\"]},\"history\":[{\"created\":\"2022-02-24T11:08:22.064775733Z\",\"comment\":\"Imported from -\"},{\"created\":\"2022-02-24T11:08:40.098139Z\"},{\"created\":\"2022-05-31T22:04:25.350304868Z\",\"created_by\":\"#(imagebuilder)\\nsleep 86400\"},{\"created\":\"2022-05-31T22:50:46.403973262Z\",\"created_by\":\"#(imagebuilder)\\nsleep 86400\"},{\"created\":\"2022-06-10T06:13:40.585458502Z\",\"created_by\":\"#(imagebuilder)\\nsleep 86400\"},{\"created\":\"2022-08-09T11:10:52.08989475Z\",\"created_by\":\"/bin/sh -c #(nop) LABEL operators.operatorframework.io.index.database.v1=/database/index.db\",\"empty_layer\":true},{\"created\":\"2022-08-09T11:10:52.94662483Z\",\"created_by\":\"/bin/sh -c #(nop) ADD file:269841b0a160e1efc86d375e6c972e0bcd4bd633ae71416a10aa256845c9070c in /database/index.db \",\"empty_layer\":true},{\"created\":\"2022-08-09T11:10:52.972533718Z\",\"created_by\":\"/bin/sh -c #(nop) EXPOSE 50051\",\"empty_layer\":true},{\"created\":\"2022-08-09T11:10:52.998969049Z\",\"created_by\":\"/bin/sh -c #(nop) ENTRYPOINT [\\\"/bin/opm\\\"]\",\"empty_layer\":true},{\"created\":\"2022-08-09T11:10:53.023791317Z\",\"created_by\":\"/bin/sh -c #(nop) CMD [\\\"registry\\\", \\\"serve\\\", \\\"--database\\\", \\\"/database/index.db\\\"]\",\"empty_layer\":true},{\"created\":\"2022-08-09T11:10:53.049063126Z\",\"created_by\":\"/bin/sh -c #(nop) LABEL com.redhat.index.delivery.version=\\\"v4.10\\\"\",\"empty_layer\":true},{\"created\":\"2022-08-09T11:10:55.994352967Z\",\"created_by\":\"/bin/sh -c #(nop) LABEL com.redhat.index.delivery.distribution_scope=\\\"prod\\\"\",\"comment\":\"FROM registry.redhat.io/openshift4/ose-operator-registry@sha256:a06748f9ebd20c32219f3f3f17355e640132ec8ff095cd1a83c7593fe34dac93\"}]}" bundles="[registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:7c8f42a9afc657bc9d53fbe0824badbc6541a9767b6ac9ce0cf2a4afca913387]"
time="2022-08-09T19:03:13Z" level=info msg="Could not find optional dependencies file" file=bundle_tmp444619333/metadata load=annotations with=bundle_tmp444619333
time="2022-08-09T19:03:13Z" level=info msg="Could not find optional properties file" file=bundle_tmp444619333/metadata load=annotations with=bundle_tmp444619333
time="2022-08-09T19:03:13Z" level=info msg="Could not find optional dependencies file" file=bundle_tmp444619333/metadata load=annotations with=bundle_tmp444619333
time="2022-08-09T19:03:13Z" level=info msg="Could not find optional properties file" file=bundle_tmp444619333/metadata load=annotations with=bundle_tmp444619333
time="2022-08-09T19:03:13Z" level=error msg="permissive mode disabled" bundles="[registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:7c8f42a9afc657bc9d53fbe0824badbc6541a9767b6ac9ce0cf2a4afca913387]" error="Bundle already added that provides package and csv"
Error: Bundle already added that provides package and csv
Usage:
  opm index add [flags]
Examples:
  # Create an index image from scratch with a single bundle image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus@sha256:a3ee653ffa8a0d2bbb2fabb150a94da6e878b6e9eb07defd40dc884effde11a0 --tag quay.io/operator-framework/monitoring:1.0.0
  
  # Add a single bundle image to an index image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus:0.15.0 --from-index quay.io/operator-framework/monitoring:1.0.0 --tag quay.io/operator-framework/monitoring:1.0.1
  
  # Add multiple bundles to an index and generate a Dockerfile instead of an image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus:0.15.0,quay.io/operator-framework/operator-bundle-prometheus:0.22.2 --generate
Flags:
  -i, --binary-image opm        container image for on-image opm command
  -u, --build-tool string       tool to build container images. One of: [docker, podman]. Defaults to podman. Overrides part of container-tool.
  -b, --bundles strings         comma separated list of bundles to add
  -c, --container-tool string   tool to interact with container images (save, build, etc.). One of: [docker, podman]
  -f, --from-index string       previous index to add to
      --generate                if enabled, just creates the dockerfile and saves it to local disk
  -h, --help                    help for add
      --mode string             graph update mode that defines how channel graphs are updated. One of: [replaces, semver, semver-skippatch] (default "replaces")
  -d, --out-dockerfile string   if generating the dockerfile, this flag is used to (optionally) specify a dockerfile name
      --permissive              allow registry load errors
  -p, --pull-tool string        tool to pull container images. One of: [none, docker, podman]. Defaults to none. Overrides part of container-tool.
  -t, --tag string              custom tag for container image being built
Global Flags:
      --skip-tls-verify   skip TLS certificate verification for container image registries while pulling bundles
      --use-http          use plain HTTP for container image registries while pulling bundles
error: build error: error building at STEP "RUN opm index add --mode replaces --bundles registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:7c8f42a9afc657bc9d53fbe0824badbc6541a9767b6ac9ce0cf2a4afca913387 --out-dockerfile index.Dockerfile --generate --from-index registry.build03.ci.openshift.org/ci-op-9rpkcvki/pipeline@sha256:67e1fecc5bdbf75c0b00e3138402952ec8f0d0b71ed16349531dd0e62b0d8371": error while running runtime: exit status 3
INFO[2022-0[8](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A8)-0[9](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A9)T19:03:18Z] Ran for [15](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A15)m41s                               
ERRO[2022-08-09T19:03:[18](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A18)Z] Some steps failed:                           
ERRO[2022-08-09T[19](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_file-integrity-operator/278/pull-ci-openshift-file-integrity-operator-master-e2e-bundle-aws/1557076083000479744#1:build-log.txt%3A19):03:18Z]
```

**Comment by rhmdnd** [comment]
> Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2115821

We're just referencing this here as related art, right? We don't have a CO specific bug, do we (I couldn't find one)?

**Review by rhmdnd — COMMENTED** [review]
/lgtm

Just one question on bug tracking, otherwise this looks good.

**Pull request merged**
